---
- en_degree: "Masters degree"
  bg_degree: "Магистърска степен"
  fr_degree: "Une maîtrise"
  ge_degree: "Master-Abschluss"
  en_specialty: "Software engineering"
  bg_specialty: "Софтуерно инженерство"
  fr_specialty: "Génie logiciel"
  ge_specialty: "Softwareentwicklung"
  en_university_name: "Technical university of Varna"
  bg_university_name: "Технически университет във Варна"
  fr_university_name: "Université technique de Varna"
  ge_university_name: "Technische Universität Warna"
  en_description: |
    Graduates of the Master's Program "Software Engineering" can work
    as applied and system programmers, web designers and developers,
    software technology consultants, internet applications and more.
  bg_description: |
    Завършилите магистърската програма "Софтуерно инженерство" могат да работят
    като приложни и системни програмисти, уеб дизайнери и разработчици,
    консултанти по софтуерни технологии, интернет приложения и други.
  fr_description: |
    Les diplômés du programme de master "Génie logiciel" peuvent travailler
    en tant que programmeurs d'applications et de systèmes, concepteurs et développeurs web,
    consultants en technologies logicielles, développeurs d'applications internet, et bien plus encore.
  ge_description: |
    Absolventen des Masterstudiengangs "Software Engineering" können unter
    anderem als Anwendungs- und Systemprogrammierer, Webdesigner und -entwickler,
    Softwaretechnologieberater oder im Bereich Internetanwendungen tätig sein.
  scroll_description: false
  image: "tu_varna.png"
  href_tooltip: "#thesis-masters"
  en_href_title: "Thesis: Design and implementation of a system for doctoral students admission and training"
  bg_href_title: "Теза: Проектиране и внедряване на система за прием и обучение на докторанти"
  fr_href_title: "Ceci : Protection et prise en charge du système de soins et de prise en charge du médecin"
  ge_href_title: "Text: Projekt und Prüfung des Systems zur Prüfung und Einsichtnahme bei Ärzten"
  date: "10-2023 - 07-2025"
  gpa: "GPA: 6.00"

- en_degree: "Bachelors degree"
  bg_degree: "Бакалавърска степен"
  fr_degree: "Licence"
  ge_degree: "Bachelor-Abschluss"
  en_specialty: "Computer and Internet technology"
  bg_specialty: "Компютърни и интернет технологии"
  fr_specialty: "Technologies informatiques et Internet"
  ge_specialty: "Computer- und Internettechnologie"
  en_university_name: "Technical university of Varna"
  bg_university_name: "Технически университет във Варна"
  fr_university_name: "Université technique de Varna"
  ge_university_name: "Technische Universität Warna"
  en_description: |
    The Objects of the Professional Activity of the Engineer with the
    specialty "SIT" are the design, development and maintenance of
    software and internet systems and applications, expanding the
    field of application of computer systems and networks and
    information technologies, successful application of modern and
    continuously developing technologies for the internet and
    expansion, distributed and parallel processing, as artificial
    intelligence.
  bg_description: |
    Предметите на професионалната дейност на инженера със специалност "СИТ"
    са проектиране, разработване и поддръжка на софтуерни и интернет системи и приложения,
    разширяване на областта на приложение на компютърните системи и мрежи и информационните технологии,
    успешно прилагане на съвременни и непрекъснато развиващи се технологии за интернет и разширяване,
    разпределена и паралелна обработка, като изкуствен интелект.
  fr_description: |
    Les objectifs de l'activité professionnelle de l'ingénieur spécialisé en " SIT " sont la conception,
    le développement et la maintenance de logiciels et de systèmes et applications internet,
    l'élargissement du champ d'application des systèmes et réseaux informatiques et des
    technologies de l'information, l'application réussie des technologies modernes et en constante évolution pour
    internet et l'informatique distribuée et parallèle, ainsi que l'intelligence artificielle.
  ge_description: |
    Die Aufgabenbereiche der beruflichen Tätigkeit des Ingenieurs mit der
    Spezialisierung „SIT“ umfassen den Entwurf, die Entwicklung und die Wartung von
    Software- und Internetsystemen und -anwendungen, die Erweiterung des
    Anwendungsbereichs von Computersystemen und -netzwerken sowie
    Informationstechnologien, die erfolgreiche Anwendung moderner und
    sich ständig weiterentwickelnder Technologien für das Internet und
    verteilte und parallele Verarbeitung sowie künstliche Intelligenz.
  scroll_description: true
  image: "tu_varna.png"
  href_tooltip: "#thesis-bachelors"
  en_href_title: "Thesis: AI-Driven Project management web app with ChatGPT 3.5"
  bg_href_title: "Теза: Уеб приложение за управление на проекти, управлявано от изкуствен интелект, с ChatGPT 3.5"
  fr_href_title: "Thèse : Application web de gestion de projet basée sur l'IA avec ChatGPT 3.5"
  ge_href_title: "Masterarbeit: KI-gestützte Webanwendung für Projektmanagement mit ChatGPT 3.5"
  date: "09-2019 - 07-2023"
  gpa: "GPA: 6.00"
